In [1]:
import sys
!{sys.executable} -m pip install lxml


from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re
#Use requests to get (as in, HTTP GET) the URL
url = 'https://www.billboard.com/charts/hot-100'
headers = {'User-Agent': 
           'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}
response = requests.get(url, headers=headers)

print(response)
#Extract the text from the page
#Use BeautifulSoup to read and parse the data, either as html or lxml
soup = BeautifulSoup(response.text, 'html.parser')

#Use prettify() to view the content and find the appropriate table
#target = soup.find(class_='table')
#pretty_target = target.prettify()
#Use pandas to read in the HTML file. HINT make-sure the above data is properly typecast.
dataframe = pd.read_html(pretty_target)

Requirement already satisfied: lxml in /opt/conda/lib/python3.8/site-packages (4.5.2)
<Response [200]>

NameError: name 'pretty_target' is not defined

In [39]:
url = 'https://www.imdb.com/chart/top/'
headers = {'User-Agent': 
           'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}
response = requests.get(url, headers=headers)

#Extract the text from the page
#Use BeautifulSoup to read and parse the data, either as html or lxml
soup = BeautifulSoup(response.text, 'html.parser')
#Use prettify() to view the content and find the appropriate table
target = soup.find(class_='chart full-width')
pretty_target = target.prettify()
#Use pandas to read in the HTML file. HINT make-sure the above data is properly typecast.
dataframe = pd.read_html(pretty_target)
#dataframe[0]
#dataframe[0].to_csv('movie_chart.csv')
dataframe[0]['year'] = 0
dataframe[0]['rank'] = 0

dataframe[0] = dataframe[0].drop(columns=['Your Rating','Unnamed: 0','Unnamed: 4'])
for index, row in dataframe[0].iterrows():
    year = re.findall(r'[0-9]{4}', row['Rank & Title'])
    dataframe[0].at[index,'year'] = int(year[0])
    dataframe[0].at[index,'rank'] = index+1
    unnecessary_rank = re.findall(r'[0-9]{0,3}.', row['Rank & Title'])[0]
    new_rank_title = row['Rank & Title'].replace(unnecessary_rank,'')
    dataframe[0].at[index,'Rank & Title'] = str(new_rank_title)
    
dataframe[0] = dataframe[0][['rank, ']]

                            Rank & Title  IMDb Rating  year  rank
0       The Shawshank Redemption  (1994)          9.2  1994     1
1                  The Godfather  (1972)          9.1  1972     2
2         The Godfather: Part II  (1974)          9.0  1974     3
3                The Dark Knight  (2008)          9.0  2008     4
4                   12 Angry Men  (1957)          8.9  1957     5
..                                   ...          ...   ...   ...
245               The Terminator  (1984)          8.0  1984   246
246                   Tangerines  (2013)          8.0  2013   247
247                      Aladdin  (1992)          8.0  1992   248
248    A Silent Voice: The Movie  (2016)          8.0  2016   249
249                   Hera Pheri  (2000)          8.0  2000   250

[250 rows x 4 columns]